# There are some rules that we would like to disable for UNIT tests
opt_in_rules:
  - line_length
# line_length: 140
disabled_rules:
  - function_body_length  # we do not care about the function bodies spanning across too many lines
  - type_body_length      # we do not care about the number of lines in the body
  - file_length           # we do not care about the file length
  - type_name             # we allow long type names in UNIT tests as they are more descriptive
  - weak_delegate         # we allow weak delegate in UNIT tests
  - identifier_name       # we allow longer identifier names in UNIT tests
  


